### PR TITLE
Prompt to download and install ffmpeg

### PR DESCRIPTION
**Pull request by DonJayamanne**
Provides a smooth install and UX, with option to download and install ffmpeg.
Also fixed a problem with the args passed to ffmpeg. 

Workflow:
* Existing functionality left intact
* Prompt to install or select install directory
* If you select new install directory, 
	* Download
	* Save this for future usage (into settings as done today)

### CODE REVIEW

**Comment by DonJayamanne** [comment]
This is a preview of what it looks like:

recorder

**Comment by arciisine** [comment]
Fantastic idea, I need to see how this fits in first, but I like the feature.

**Comment by DonJayamanne** [comment]
My plan is to get this to the stage so we can promote it to users of our [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) to  use this extension to capture screen shots &/or gifs (when filing issues, etc).

And thanks for the great extension.

**Comment by arciisine** [comment]
I'll get this reviewed today and hopefully merged, though I may have some feedback.  Thanks again

**Comment by arciisine** [comment]
@DonJayamanne so I looked at the PR, and it came in quite heavy, especially on the dependency side.  I ended up implementing ffmpeg download functionality in @arciisine/screen-recorder (the base lib) to reduce the number of included libs (ffmpeg installer is quite heavy).  After that I implemented the functionality that you had done in your PR.   Please take a look and let me know if this fits your needs.

I really like what you did and appreciate the effort.  I plan on using some of the patterns int he PR in my other plugins.

**Comment by DonJayamanne** [comment]
> . Please take a look and let me know if this fits your needs.

Did you update this PR or create another?

**Comment by arciisine** [comment]
@DonJayamanne I ended up doing the work and pushing into master.

**Comment by DonJayamanne** [comment]
You didn't give me a chance to make any changes to my PR!
Oh well.

**Comment by arciisine** [comment]
Sorry about that. I wanted to go through PR feedback but I realized the changes were going to be too extensive for that to be effective.

**Pull request closed without merging**
